### ISSUE TITLE
Can't resize some fonts in blocks

### ISSUE THREAD

**Issue by lumieria** [Mobirise/Mobirise#58]
I suspect the "Bold," and "Italic" functions are supposed to be part of the Character format popup menu (the one containing "Font," "Color," and "Size"), but they are appearing as a separate popup and pre-empting those options instead.  This severely limits the creative potential of the blocks it affects.

**Comment by Mobirise** [comment]
To **Bold** or _Italic_ the part of text, just select this part and press "B" or "I" button. You can also use "Ctrl+B" or "Ctrl+I".

**Comment by lumieria** [comment]
The problem isn't whether or not I'm able to bold or italic text.  As the issue states, it is the fact that the BOLD/ITALIC popup menu HIDES/DISABLES the rest of the font options, which seem to be in their own menu.  I was merely suggesting the potential source of the problem, in the hopes of getting a fix.

**Comment by PINU1981** [comment]
I have a similar problem please check screencast here when i try scrolling the dialog seems stuck on only the top options https://screencast-o-matic.com/watch/cFfhXdDdqp

**Comment by Mobirise** [comment]
This is fixed in v4.5, please update and try.
