### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by msitta** [Mobirise/Mobirise#6]
While running Wine, I can't install Mobirise under Ubuntu 14.04. The only mention is of an "error while opening package". Are you planning on releasing a Linux Version of Mobirise?

Can I still install it with Ubuntu 14.04?

Please, help...

**Comment by Mobirise** [comment]
Mobirise works ok with WINE on Linux
http://forums.mobirise.com/discussion/comment/2770/
