### ISSUE TITLE
Publish to GitHub Pages stopped working after update to latest version 

### ISSUE THREAD

**Issue by buzag** [Mobirise/Mobirise#62]
Export to GitHub Pages feature:
Upgraded, was working fine after a couple times of successful publishing began to freeze.

<img width="599" alt="screen shot 2017-08-26 at 12 18 16" src="https://user-images.githubusercontent.com/292264/29740538-0678b7ca-8a59-11e7-8140-aeed02e1530e.png">

Export to local and preview works fine, I can add exported to GH Pages manually via Git Desktop.

**Comment by buzag** [comment]
Found a workaround.
It's probably because of expired credentials/wrong password/authentication problems.

By uploading, I change my username to get to the "Give username and password" pop-up. Then I set my correct credentials and it works.

**Comment by nicolegithub2** [comment]
I am having the same problem. I tried changing my username and it still didn't work.

**Comment by aleqsio** [comment]
Experiencing the same issue, seems like username + password works ok, but pasting in a github token just hangs on preparing the last page.

**Comment by cvng** [comment]
Same as @aleqsio , using a personal access token freeze GH deploy. How do we clear Mobirise credentials cache?

**Comment by ZorroGordo** [comment]
I'm having the same problem. The credentials seems to work as when I put incorrect password it doesn't close the login pop-up. Did anyone figure out the problem and how to fix it?
