### ISSUE TITLE
Install of the builder's program impossible because of Norton anti virus

### ISSUE THREAD

**Issue by goalsurfer** [Mobirise/Mobirise#65]
When I double click on the install program "Mobirise4-setup.exe" I get a Norton popup telling me that it is inactive and that for finding help I should open it in its principal window.  But what is its principal window?  There is no support on the mobisrise.com, or .net site as far as I see.  These templates gave no problem.

I'm a user of the ordinary bootstrap which I use without problems since a couple of years and now I want to try this out just to see if I can't make more beautiful designs with it.  It's really the first time I'm stuck.

**Comment by Mobirise** [comment]
Hi!

What version of mobirise you use?
Please send a screenshot.

Best
Tom N.

**Comment by goalsurfer** [comment]
Hello,

Sorry I didn't pay attention to the version.  I remember that one day I met a banner again I did a new installation and now I have a working version, namely 4.6.2.  See screenshot.  

![screenshot](https://user-images.githubusercontent.com/1173654/34584096-a68db6ea-f19a-11e7-9a70-4f6fe2e09760.png)
