### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by tonymontana1** [Mobirise/Mobirise#68]
Hello Mobirise Team!
 
We have prepared for you report on the bugs of the program Mobirise.
 
The PDF's contains the references of your users to the form on our website - Mobirise-Bugs.com

https://mobirise-bugs.com/first_report_mobirise_bugs.pdf
https://mobirise-bugs.com/chapter_two.pdf
 
Get and sign :)

**Comment by Mobirise** [comment]
Ok, thanks!
