### ISSUE TITLE
Translator for content and Github integration +

### ISSUE THREAD

**Issue by kosirm** [Mobirise/Mobirise#69]
Hi, first of all, Mobirise is THE best website builder imho.
I have two questions/requests:

1.  github integration: it is great I can upload site to github pages, but it would be even better, if I could also **open site from there**. Please consider this!
2. translator: it is great that I can translate Mobirise, but I would like to **translate website content** (create multilingual site). Please consider this also!
All the best to contributors!

**Comment by cvng** [comment]
@kosirm the fact is, once you get your website into the github pipeline, you can perform any operations after deployment, like automated translation, but I agree it requires developer skills

**Comment by kosirm** [comment]
@cvng Thanks, everything you said is correct! I was thinking about the creation of a multilingual website from within Mobirise editor... I could develop a multilanguage website, but I'm not sure, how someone except me could use/edit website text inside Mobirise then... I don't even think that I could use Mobirise editor for editing text in multiple languages ...
I have some ideas, how this could be done. I even made some attempts to achieve this with javascript on the page, but overall it was unsuccessful... because I can use my javascript only on the website, not inside Mobirise editor.

**Comment by cvng** [comment]
Mobirise editor is efficient for quickly bootstrapping a website. 

Any extra operations, like automated translated rather be done outside of it, there are already plenty tools to achieve this goal.

**Comment by kosirm** [comment]
I agree. But it _could_ be better, don't you think? Because translator extension is done pretty well and it could be extended to translate content values as well. But it's just an idea, no biggie 😄

**Comment by Mobirise** [comment]
Thanks for the idea. I think it's possible to modify the translator extension to translate the site content. We'll ad this to our to-do list.

**Comment by kosirm** [comment]
That's great to know! Thanks!
