### ISSUE TITLE
Bug in gallery block!

### ISSUE THREAD

**Issue by defcon8** [Mobirise/Mobirise#70]
There is a bug in the "Gallery" block. When you try to rearrange tiles by dragging them from left to right (in the "Gallery" section of the block properties dialog), tiles get lost or swapped and weird (unwanted) behaviour occurs. It's very annoying and makes mobirise almost unusable for my purpose.

#Mobirise Version: 4.6.5.
![schermafbeelding 2018-02-23 om 11 36 21](https://user-images.githubusercontent.com/3636349/36590271-66467dcc-188e-11e8-89c4-34a3ff3c925e.png)
![schermafbeelding 2018-02-23 om 11 36 41](https://user-images.githubusercontent.com/3636349/36590276-6800e7d8-188e-11e8-9f42-73775a891b73.png)

**Comment by ndy-01** [comment]
Also getting this as well. Agreed, makes it hard to use Mobirise for what I want as it is really screwing up my webpages.

**Comment by Byteler** [comment]
I met it with Mobirse3, not Mobirise4. And you?

**Comment by Mobirise** [comment]
This is fixed Mobirise v4.7, themes "M4" and "AMP".
