### ISSUE TITLE
why does the publish script randomly generate a line in each html?

### ISSUE THREAD

**Issue by sunilkpai** [Mobirise/Mobirise#72]
The line looks something like:

`<section class="engine"><a href="https://mobirise.ws/l">free html site maker</a></section><section class="mbr-section content4 cid-qLxJrCfsOD" id="content4-v">`

This line keeps randomly changing whenever we publish, making it virtually impossible to collaborate 😢 . Is there anything that can be done to fix this so that it generates the same line?

Thanks!

**Comment by schroef** [comment]
its in one of the script, i came across it anf took it out
