### ISSUE TITLE
Who are you?

### ISSUE THREAD

**Issue by jasonbrown1965** [Mobirise/Mobirise#74]
Loving the look and apparent simplicity of your app. I say 'apparent' because I have neither downloaded nor installed. Moborise just a little too .. secret for me. Here's a list of problems:

1. Closed source software
2. No about us page
3. No team, leadership profiles
4. No GPRD cookie alert
5. Secret godaddy WHOIS ~ with blank registrant, admin and technical fields
6. Vague, vague postal code only ~ don't EU biz have to declare full address?
7. Claims Netherlands base but registered under UK godaddy
8. No link to this Github on Mobirise website
9. A very short (less than 1 page) EULA
10. No privacy policy!

Hate to even suggest 'something rotten' in whichever state/s the anonymous Mobirise team actually comes from, and one or two omissions is normal. But collectively? Hmmmmnnnnn ... a please explain, please. 

. . .

**Comment by Mobirise** [comment]
Hi!
Nice to meet you too, Jason Brown from New Zealand :)

**Comment by jasonbrown1965** [comment]
Any update on the questions raised above?

**Comment by lexoyo** [comment]
It is closed source indeed :-/
Not clear to me as it is on GitHub with the same name
