### ISSUE TITLE
85/100 malicious analysis rating 

### ISSUE THREAD

**Issue by jasonbrown1965** [Mobirise/Mobirise#75]
Further to my concerns about a lack of a privacy policy or other legit information on the website, an analysis of the Mobirise download alleges an 85/100 score for potential malicious action, see:

https://www.hybrid-analysis.com/sample/bad2749c962b6a7888badaea615b84c9e7aca584a0e295f7df6acd0d4ba6bc15/5b7f884f7ca3e1473e1d9e53

There may be perfectly reasonable explanations for all these (including analyst sites spruiking anti-malware software), but that's way above my paygrade. Nonetheless, explanations and assurances should be sought and given.

. . .

**Comment by Mobirise** [comment]
Hi!
Mobirise software is 100% clean, please see:

https://www.virustotal.com/en/url/07f80bef7e1cde3123488200bc3b1f4d559400da5e7089f4d19f18224671b0d6/analysis/

https://www.virustotal.com/en/url/4868476f09ac64a84ad969751146e9e78e4d423f12531b446d475a7c963ad221/analysis/1536051895/

Privacy policy is here:
https://mobirise.com/privacy.html
