### ISSUE TITLE
Website page goes missing after any changes made in GitHub Pages!

### ISSUE THREAD

**Issue by irazirfan** [Mobirise/Mobirise#81]
I am facing this problem whenever I do changes to my GitHub site pages.
My website page goes missing after any changes made. I had to set a theme from GitHub settings each time to solve this issue.
![issue](https://user-images.githubusercontent.com/36075533/72551478-1c202880-38bf-11ea-828a-3acd9d3d65af.PNG)

**Comment by Starbors** [comment]
This its a company itself which HAS AN APP not a website.
